name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch for release"
        required: true
        default: "master"
      tag_name:
        description: "Tag name to use for the release"
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 1  # last commit. Change to 0 to get all git history

      - name: Create zip from RumiCar folder
        run: |
          cd ArduinoAndESP32/Libraries/
          zip -r "release_${{ github.event.inputs.tag_name}}.zip" RumiCar

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: Release ${{ github.event.inputs.tag_name }}
          files: ArduinoAndESP32/Libraries/release_${{ github.event.inputs.tag_name}}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
